BinaryStudioAcademy/bsa-2022-vse-bude

packages/backend/package.json
packages/frontend/package.json
packages/shared/package.json

Fixed an error that can't runs prettier script because of invalid brackets in path pattern.

VB-48: fix prettier script

---

packages/frontend/components/primitives/tooltip/component.tsx

VB-110: fix tooltip overflow screen edges

---

packages/frontend/components/header/profile-info/styles.ts
packages/frontend/components/primitives/avatar/styles.ts
packages/frontend/components/primitives/popover/styles.ts

VB-144: Fix/bug with dropdown

---

packages/mobile/package-lock.json
packages/mobile/package.json
packages/mobile/src/components/build-info/build-info.tsx
packages/mobile/src/components/components.ts
packages/mobile/src/screens/home/home.tsx

VBM-117: add build & version number on home screen

---

packages/frontend/components/header/profile-info/sub-components/popover-content.tsx
packages/frontend/public/locales/en/common.json
packages/frontend/public/locales/ua/common.json

VB-177: Fix/menu is not localized

---

packages/frontend/components/primitives/popover/styles.ts

VB-186: Fix/popover have wrong position

---

packages/frontend/components/primitives/menu-dropdown/styles.ts

VB-189: added nowrap to dropdown items

---

packages/mobile/src/localization/languages/en/common.ts
packages/mobile/src/localization/languages/ua/common.ts
packages/mobile/src/store/middlewares/error-handler.ts
packages/mobile/src/store/middlewares/errors-handler.ts
packages/mobile/src/store/middlewares/middlewares.ts
packages/mobile/src/store/store.ts

https://user-images.githubusercontent.com/69375560/187253657-f08b9039-cb54-42f8-9692-0c4644a98846.mp4

VBM-101: server errors handling

---

packages/frontend/components/home/charity-section/component.tsx
packages/frontend/components/home/charity-section/styles.ts
packages/frontend/components/home/lot-section/component.tsx
packages/frontend/components/home/lot-section/styles.ts

VB-174: Fix/popular lots scroll

---

packages/mobile/src/components/components.ts
packages/mobile/src/components/scroll-view/scroll-view.tsx

https://user-images.githubusercontent.com/69375560/187704021-4ffba339-b9ed-4664-bf0c-ce38b56def18.mp4

VBM-116: enable button press while keyboard on

---

packages/mobile/src/components/flag-background-view/flag-background-view.tsx
packages/mobile/src/screens/welcome/components/components.ts
packages/mobile/src/screens/welcome/components/stamp/stamp.tsx
packages/mobile/src/screens/welcome/components/stamp/style.ts
packages/mobile/src/screens/welcome/styles.ts
packages/mobile/src/screens/welcome/welcome.tsx
packages/shared/src/common/enums/theme/color-palette.ts

VBM-114: welcome screen fix

---

packages/frontend/components/item/countdown-timer/component.tsx

VB-217: Fix/auction timer

---

packages/mobile/src/screens/account/account.tsx
packages/mobile/src/store/auth/actions.ts
packages/mobile/src/store/auth/common.ts
packages/mobile/src/store/auth/reducer.ts

https://user-images.githubusercontent.com/10462332/187962081-624922a0-7429-4dcc-b651-ff6ede7027d6.mov

VBM-120: add logout

---

packages/frontend/components/home/charity-section/component.tsx
packages/frontend/components/home/lot-section/component.tsx

VB-248: fix/products-slider

---

packages/mobile/src/screens/personal-info/components/personal-info-form/personal-info-form.tsx

VBM-122: add a show/hide password icon

---

packages/frontend/components/home/category-section/styles.ts
packages/frontend/components/home/charity-section/component.tsx
packages/frontend/components/home/charity-section/styles.ts
packages/frontend/components/home/lot-section/component.tsx
packages/frontend/components/home/lot-section/styles.ts
packages/frontend/components/home/section-layout/styles.ts
packages/frontend/components/primitives/container/styles.ts
packages/frontend/components/product/card/styles.ts

320PX:
768px:
1024px
1440px and more:

VB-218: fix lot slider

---

packages/frontend/components/product/timer/component.tsx
packages/frontend/helpers/time.ts

VB-257: Fix/negative numbers in product card

---

packages/frontend/components/primitives/menu-dropdown/styles.ts
packages/frontend/components/primitives/select/component.tsx
packages/frontend/components/primitives/select/index.ts
packages/frontend/components/primitives/select/styles.ts
packages/frontend/components/primitives/select/types.ts

VB-83: added select

---

packages/mobile/src/screens/welcome/components/stamp/stamp.tsx
packages/mobile/src/screens/welcome/components/stamp/style.ts
packages/mobile/src/screens/welcome/styles.ts
packages/mobile/src/screens/welcome/welcome.tsx

VBM-130: screen scale position fixed

---

packages/mobile/src/components/photo-picker-modal/photo-picker-modal.tsx
packages/mobile/src/localization/languages/en/common.ts
packages/mobile/src/localization/languages/ua/common.ts

VBM-128: add localization to avatar menu

---

packages/mobile/src/localization/languages/en/common.ts
packages/mobile/src/localization/languages/ua/common.ts
packages/mobile/src/navigation/tabs/tabs.navigation.tsx

VBM-143: tabBar localization added

---

packages/mobile/src/helpers/category/format-category-for-dropdown.ts
packages/mobile/src/helpers/helpers.ts
packages/mobile/src/screens/new-item/components/new-auction-form/new-auction-form.tsx
packages/mobile/src/screens/new-item/components/new-item-form/new-item-form.tsx

VBM-149: [Make a Post] drop-down list of categories

---

packages/frontend/helpers/time.ts

VB-317: Fix/product-timer

---

packages/frontend/public/locales/ua/common.json

VB-366: fix/misprint-in-the-menu

---

packages/mobile/src/screens/product-info/components/price-block/lot-price-block.tsx
packages/mobile/src/screens/product-info/components/price-block/product-price-block.tsx

VBM-150: currency position fixed

---

packages/mobile/src/localization/languages/en/screens.ts
packages/mobile/src/localization/languages/ua/screens.ts
packages/mobile/src/screens/auth/components/sign-in-form/sign-in-form.tsx

VBM-146: position forgot password fixed

---

packages/backend/package-lock.json
packages/frontend/components/item/item-info-auction/component.tsx

VB-374: Fix/place a bid

---

packages/frontend/components/filter/filter-header/filter-popover.tsx

VB-391: Fix/number-in-filters-returns-to-old-data

---

packages/frontend/components/primitives/button-group/styles.ts

VB-389: Fix/filter-buttons-layout

---

packages/mobile/src/components/product/product.tsx
packages/mobile/src/components/product/styles.ts
packages/mobile/src/screens/product-info/components/price-block/lot-price-block.tsx
packages/mobile/src/screens/product-info/components/price-block/price-wrapper.tsx
packages/mobile/src/screens/product-info/components/price-block/styles.ts

VBM-187: fix card layout

---

packages/mobile/src/screens/product-info/components/description/styles.ts

VBM-191: localization spacing fixed

---

packages/mobile/src/screens/product-info/components/seller-info/seller-info.tsx
packages/mobile/src/screens/product-info/components/seller-info/social-button.tsx

VBM-206: hide empty phone

---

packages/mobile/src/screens/product-info/components/seller-info/seller-info.tsx

VBM-194: add seller last name

---

packages/mobile/src/screens/auth/components/sign-up-form/sign-up-form.tsx

order changed, localization seems fine

VBM-209: Fix/change sign-up fields order

---

packages/mobile/src/screens/my-list/my-list.tsx

VBM-231: remove title in the top of the screen

---

packages/mobile/src/components/product/product.tsx

VBM-213: fix position of divider

---

packages/mobile/src/navigation/drawer/components/menu/drawer-menu.tsx
packages/mobile/src/store/categories/reducer.ts
packages/mobile/src/store/categories/selectors.ts

https://user-images.githubusercontent.com/69375560/191228524-b689d73d-41a2-49ce-b971-ff841371022b.mp4

VBM-205: add server DTO categories

---

packages/mobile/src/common/types/navigation/drawer-navigation-param-list.ts
packages/mobile/src/common/types/navigation/navigation-props.ts
packages/mobile/src/common/types/navigation/navigation.ts
packages/mobile/src/common/types/navigation/root-navigation-param-list.type.ts
packages/mobile/src/common/types/types.ts
packages/mobile/src/components/burger-menu/burger-menu.tsx
packages/mobile/src/navigation/drawer/drawer.navigation.tsx
packages/mobile/src/navigation/screen-options/items-screen-options.tsx

https://user-images.githubusercontent.com/69375560/191009352-c5115c24-b466-4a62-9ebb-21b50a80ab2d.mp4

VBM-204: drawer trigger changed

---

packages/mobile/src/common/enums/navigation/main-screen-name.enum.ts

Forgot to change name in MainScreen

VBM :screen name fix

---

packages/mobile/src/components/product/product.tsx

https://user-images.githubusercontent.com/69375560/191495654-a08f1bb2-7a67-4c0b-8dc9-79faa1bf446b.mp4

VBM-230: remove button in products list

---

packages/mobile/src/navigation/tabs/tabs.navigation.tsx

VBM-248: add condition avatar in tab menu

---

packages/mobile/src/components/product/product.tsx

VBM-252: default image for products in lists added
